name: Lint lua files
on:
  push:
    paths:
      - "**.lua"
  pull_request:
    paths:
      - "**.lua"

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting with stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.TOKEN }}
          version: latest
          # args passed to stylua
          args: --check -f config/nvim/.stylua.toml .
